# Generated by Django 4.2.4 on 2023-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_instance', 'En instance'), ('non_livre', 'Non livré'), ('livre', 'Livré')], max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
